//LOGIN AND LOGOUT
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

//SET INFO CLIENTE
export const SET_INFO_CLIENTE = "SET_INFO_CLIENTE";

export const SET_CUPON_CLIENTE = "SET_CUPON_CLIENTE";

export const SET_TOTAL_REFERIDOS_CLIENTE = "SET_TOTAL_REFERIDOS_CLIENTE";