//LOGIN AND LOGOUT
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

//SET INFO CLIENTE
export const SET_INFO_CLIENTE = "SET_INFO_CLIENTE";

export const SET_CUPON_CLIENTE = "SET_CUPON_CLIENTE";

export const SET_TOTAL_REFERIDOS_CLIENTE = "SET_TOTAL_REFERIDOS_CLIENTE";


//Actions to suscription
export const S_ADD_TO_CART = "S_ADD_TO_CART";
export const S_ADD_ONE_PRODUCT = "S_ADD_ONE_PRODUCT";
export const S_REMOVE_ONE_FROM_CART = "S_REMOVE_ONE_FROM_CART";
export const S_REMOVE_ALL_FROM_CART = "S_REMOVE_ALL_FROM_CART";
export const S_CLEAR_CART = "S_CLEAR_CART";
export const S_FILL_CART = "S_FILL_CART";